#ifndef __LASERMISC_H
#define __LASERMISC_H

#include "stm32f4xx_hal.h"
#include <math.h>
#include "arm_math.h"

#define MISC_GPIO_RELAY1	GPIO_PIN_4	// relay 1
#define MISC_GPIO_RELAY2	GPIO_PIN_5	// relay 2
#define MISC_GPIO_RELAY3	GPIO_PIN_6	// relay 3
#define MISC_GPIO_RELAY4	GPIO_PIN_7	// relay 4

#define __MISC_RELAY1_ON()	HAL_GPIO_WritePin(GPIOB, MISC_GPIO_RELAY1, GPIO_PIN_SET)
#define __MISC_RELAY2_ON()	HAL_GPIO_WritePin(GPIOB, MISC_GPIO_RELAY2, GPIO_PIN_SET)
#define __MISC_RELAY3_ON()	HAL_GPIO_WritePin(GPIOB, MISC_GPIO_RELAY3, GPIO_PIN_SET)
#define __MISC_RELAY4_ON()	HAL_GPIO_WritePin(GPIOB, MISC_GPIO_RELAY4, GPIO_PIN_SET)

#define __MISC_RELAY1_OFF()	HAL_GPIO_WritePin(GPIOB, MISC_GPIO_RELAY1, GPIO_PIN_RESET)
#define __MISC_RELAY2_OFF()	HAL_GPIO_WritePin(GPIOB, MISC_GPIO_RELAY2, GPIO_PIN_RESET)
#define __MISC_RELAY3_OFF()	HAL_GPIO_WritePin(GPIOB, MISC_GPIO_RELAY3, GPIO_PIN_RESET)
#define __MISC_RELAY4_OFF()	HAL_GPIO_WritePin(GPIOB, MISC_GPIO_RELAY4, GPIO_PIN_RESET)

#endif